-- Seed orders by date range (11 -> 23) for dashboard/testing.
-- MySQL 8+ (uses recursive CTE).
--
-- Usage:
--   1) Adjust @from_date / @to_date (inclusive)
--   2) Ensure payment_id, service_id, user_id, book_id exist in your DB
--   3) Run this file in MySQL client

USE `kebookdb`;

SET @from_date = DATE('2026-04-11');
SET @to_date = DATE('2026-04-23');

-- Optional cleanup for re-run (only rows generated by this script)
DELETE oi
FROM order_items oi
JOIN orders o ON o.id = oi.order_id
WHERE o.note LIKE 'Seed 11-23 day%';

DELETE FROM orders
WHERE note LIKE 'Seed 11-23 day%';

-- Generate one order per day in range [@from_date, @to_date].
-- If you need exactly 14 days, set @to_date = DATE('2026-04-24').
INSERT INTO orders (
  note,
  order_date,
  phone_number,
  shipping_address,
  status,
  total_price,
  payment_id,
  service_id,
  user_id
)
WITH RECURSIVE date_series AS (
  SELECT @from_date AS d
  UNION ALL
  SELECT DATE_ADD(d, INTERVAL 1 DAY)
  FROM date_series
  WHERE d < @to_date
)
SELECT
  CONCAT('Seed 11-23 day ', DATE_FORMAT(d, '%Y-%m-%d')) AS note,
  TIMESTAMP(d, MAKETIME(9 + (DAY(d) MOD 10), (DAY(d) * 7) MOD 60, 0)) AS order_date,
  CONCAT('09', LPAD(DAY(d), 2, '0'), '000000') AS phone_number,
  CONCAT('Auto seed address day ', DATE_FORMAT(d, '%d/%m')) AS shipping_address,
  'COMPLETED' AS status,
  CASE
    WHEN DAY(d) MOD 3 = 0 THEN 120000 * 2 + 155000 * 1
    WHEN DAY(d) MOD 3 = 1 THEN 150000 * 1 + 99000 * 2
    ELSE 110000 * 2 + 95000 * 1
  END AS total_price,
  1 AS payment_id,
  1 AS service_id,
  25 AS user_id
FROM date_series;

-- Attach 2 line items per seeded order.
-- book_id set: 51, 52, 55, 60, 62, 65 (adjust if needed).
INSERT INTO order_items (price, quantity, book_id, order_id, is_deleted, deleted_at)
SELECT
  CASE
    WHEN DAY(o.order_date) MOD 3 = 0 THEN 120000
    WHEN DAY(o.order_date) MOD 3 = 1 THEN 150000
    ELSE 110000
  END AS price,
  CASE
    WHEN DAY(o.order_date) MOD 3 = 0 THEN 2
    WHEN DAY(o.order_date) MOD 3 = 1 THEN 1
    ELSE 2
  END AS quantity,
  CASE
    WHEN DAY(o.order_date) MOD 3 = 0 THEN 51
    WHEN DAY(o.order_date) MOD 3 = 1 THEN 52
    ELSE 55
  END AS book_id,
  o.id AS order_id,
  b'0' AS is_deleted,
  NULL AS deleted_at
FROM orders o
WHERE o.note LIKE 'Seed 11-23 day%';

INSERT INTO order_items (price, quantity, book_id, order_id, is_deleted, deleted_at)
SELECT
  CASE
    WHEN DAY(o.order_date) MOD 3 = 0 THEN 155000
    WHEN DAY(o.order_date) MOD 3 = 1 THEN 99000
    ELSE 95000
  END AS price,
  CASE
    WHEN DAY(o.order_date) MOD 3 = 0 THEN 1
    WHEN DAY(o.order_date) MOD 3 = 1 THEN 2
    ELSE 1
  END AS quantity,
  CASE
    WHEN DAY(o.order_date) MOD 3 = 0 THEN 60
    WHEN DAY(o.order_date) MOD 3 = 1 THEN 65
    ELSE 62
  END AS book_id,
  o.id AS order_id,
  b'0' AS is_deleted,
  NULL AS deleted_at
FROM orders o
WHERE o.note LIKE 'Seed 11-23 day%';

-- Quick check
SELECT
  DATE(order_date) AS d,
  COUNT(*) AS orders_count,
  SUM(total_price) AS revenue
FROM orders
WHERE note LIKE 'Seed 11-23 day%'
GROUP BY DATE(order_date)
ORDER BY d;
